# Generated by Django 5.1.5 on 2026-01-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='tone_confidence',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='tone_emotion',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='tone_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailevent',
            name='event_type',
            field=models.CharField(choices=[('email.new', 'New Email'), ('email.spam_classified', 'Spam Classified'), ('email.priority_assigned', 'Priority Assigned'), ('email.summary', 'Summary'), ('email.action_items', 'Action Items'), ('email.tone_analyzed', 'Tone Analyzed')], max_length=64),
        ),
    ]
